### ISSUE TITLE
thread 'main' panicked at 'index out of bounds

### ISSUE THREAD

**Issue by judomat** [Kindelia/HVM#115]
I'm writing an Agda to HVM compiler, when I compile this Agda code:
```

open import Agda.Builtin.Bool
open import Agda.Builtin.Nat

variable A B : Set

data List (A : Set) : Set where
  [] : List A
  _::_ : A → List A → List A

infixr 5 _::_

if_then_else_ : {A : Set} → Bool → A → A → A
if true then x else y = x
if false then x else y = y

filter : (A → Bool) → List A → List A
filter p [] = []
filter p (x :: xs) = if p x then x :: filter p xs else filter p xs

_++_ : List A → List A → List A
[]        ++ ys = ys
(x :: xs) ++ ys = x :: (xs ++ ys)

_>>=_ : List A → (A → List B) → List B
[]        >>= f = []
(x :: xs) >>= f = f x ++ (xs >>= f)

range : Nat → Nat → List Nat
range x y = go (suc y - x) x
  where
    go : Nat → Nat → List Nat
    go zero    _ = []
    go (suc m) n = n :: go m (suc n)

record Triple : Set where
  constructor triple
  field
    fst snd trd : Nat

alltriples : Nat → List Triple
alltriples top = range 1 top >>= λ z → range 1 z >>= λ y → range 1 y >>= λ x → (triple x y z) :: []

cartesian : Triple → Bool
cartesian (triple x y z) = x * x + y * y == z * z

triples : Nat → List Triple
triples top = filter cartesian (alltriples top)

sumall : List Triple → Nat
sumall [] = 0
sumall (triple x y z :: xs) = x + y + z + sumall xs

test1 = sumall (triples 20) -- evaluates to 33638

main = test1
```
The resulting HVM code is:
```
(X5Bx5D_0) = (X5Bx5D)

(Z_x3Ax3A__0) = (@a (@b (Z_x3Ax3A__2 a b)))
(Z_x3Ax3A__1 a) = (@b (Z_x3Ax3A__2 a b))
(Z_x3Ax3A__2 a b) = (Z_x3Ax3A_ a b)

(If_then_else__0) = (@a (@b (@c (@d (If_then_else__4 a b c d)))))
(If_then_else__1 a) = (@b (@c (@d (If_then_else__4 a b c d))))
(If_then_else__2 a b) = (@c (@d (If_then_else__4 a b c d)))
(If_then_else__3 a b c) = (@d (If_then_else__4 a b c d))
(If_then_else__4 a b c d) = (If_then_else__split_b_4 a b c d)
	(If_then_else__split_b_4 a (False) c d) = let b = (False); (d)
	(If_then_else__split_b_4 a (True) c d) = let b = (True); (c)

(Filter_0) = (@a (@b (@c (Filter_3 a b c))))
(Filter_1 a) = (@b (@c (Filter_3 a b c)))
(Filter_2 a b) = (@c (Filter_3 a b c))
(Filter_3 a b c) = (Filter_split_c_3 a b c)
	(Filter_split_c_3 a b (X5Bx5D)) = let c = (X5Bx5D); (c)
	(Filter_split_c_3 a b (Z_x3Ax3A_ d e)) = let c = (Z_x3Ax3A_ d e); (If_then_else__4 Matteo ((b) (d)) (Z_x3Ax3A__2 (d) (Filter_3 Matteo (b) (e))) (Filter_3 Matteo (b) (e)))

(Z_x2Bx2B__0) = (@a (@b (@c (Z_x2Bx2B__3 a b c))))
(Z_x2Bx2B__1 a) = (@b (@c (Z_x2Bx2B__3 a b c)))
(Z_x2Bx2B__2 a b) = (@c (Z_x2Bx2B__3 a b c))
(Z_x2Bx2B__3 a b c) = (Z_x2Bx2B__split_b_3 a b c)
	(Z_x2Bx2B__split_b_3 a (X5Bx5D) c) = let b = (X5Bx5D); (c)
	(Z_x2Bx2B__split_b_3 a (Z_x3Ax3A_ d e) c) = let b = (Z_x3Ax3A_ d e); (Z_x3Ax3A__2 (d) (Z_x2Bx2B__3 Matteo (e) (c)))

(Z_x3Ex3Ex3D__0) = (@a (@b (@c (@d (Z_x3Ex3Ex3D__4 a b c d)))))
(Z_x3Ex3Ex3D__1 a) = (@b (@c (@d (Z_x3Ex3Ex3D__4 a b c d))))
(Z_x3Ex3Ex3D__2 a b) = (@c (@d (Z_x3Ex3Ex3D__4 a b c d)))
(Z_x3Ex3Ex3D__3 a b c) = (@d (Z_x3Ex3Ex3D__4 a b c d))
(Z_x3Ex3Ex3D__4 a b c d) = (Z_x3Ex3Ex3D__split_c_4 a b c d)
	(Z_x3Ex3Ex3D__split_c_4 a b (X5Bx5D) d) = let c = (X5Bx5D); (c)
	(Z_x3Ex3Ex3D__split_c_4 a b (Z_x3Ax3A_ e f) d) = let c = (Z_x3Ax3A_ e f); (Z_x2Bx2B__3 Matteo ((d) (e)) (Z_x3Ex3Ex3D__4 Matteo Matteo (f) (d)))

(Range_0) = (@a (@b (Range_2 a b)))
(Range_1 a) = (@b (Range_2 a b))
(Range_2 a b) = (Go_4 Matteo Matteo (Z_x2D__2 (+ 1 (b)) (a)) (a))

(Go_0) = (@a (@b (@c (@d (Go_4 a b c d)))))
(Go_1 a) = (@b (@c (@d (Go_4 a b c d))))
(Go_2 a b) = (@c (@d (Go_4 a b c d)))
(Go_3 a b c) = (@d (Go_4 a b c d))
(Go_4 a b c d) = (Go_split_c_4 a b c d)
	(Go_split_c_4 a b 0 d) = let c = 0; (X5Bx5D_0)
	(Go_split_c_4 a b c d) = let e = (Go_e_4 a b c d); (Z_x3Ax3A__2 (d) (Go_4 Matteo Matteo (e) (+ 1 (d))))
	(Go_e_4 a b c d) = (- (c) 1)

(Fst_0) = (@a (Fst_1 a))
(Fst_1 a) = (Fst_split_a_1 a)
	(Fst_split_a_1 (Triple b c d)) = let a = (Triple b c d); (b)

(Snd_0) = (@a (Snd_1 a))
(Snd_1 a) = (Snd_split_a_1 a)
	(Snd_split_a_1 (Triple b c d)) = let a = (Triple b c d); (c)

(Trd_0) = (@a (Trd_1 a))
(Trd_1 a) = (Trd_split_a_1 a)
	(Trd_split_a_1 (Triple b c d)) = let a = (Triple b c d); (d)

(Triple_0) = (@a (@b (@c (Triple_3 a b c))))
(Triple_1 a) = (@b (@c (Triple_3 a b c)))
(Triple_2 a b) = (@c (Triple_3 a b c))
(Triple_3 a b c) = (Triple a b c)

(Alltriples_0) = (@a (Alltriples_1 a))
(Alltriples_1 a) = (Z_x3Ex3Ex3D__4 Matteo Matteo (Range_2 1 (a)) (@b (Z_x3Ex3Ex3D__4 Matteo Matteo (Range_2 1 (b)) (@c (Z_x3Ex3Ex3D__4 Matteo Matteo (Range_2 1 (c)) (@d (Z_x3Ax3A__2 (Triple_3 (d) (c) (b)) (X5Bx5D_0))))))))

(Cartesian_0) = (@a (Cartesian_1 a))
(Cartesian_1 a) = (Cartesian_split_a_1 a)
	(Cartesian_split_a_1 (Triple b c d)) = let a = (Triple b c d); (== (+ (* (b) (b)) (* (c) (c))) (* (d) (d)))

(Triples_0) = (@a (Triples_1 a))
(Triples_1 a) = (Filter_3 Matteo (Cartesian_0) (Alltriples_1 (a)))

(Sumall_0) = (@a (Sumall_1 a))
(Sumall_1 a) = (Sumall_split_a_1 a)
	(Sumall_split_a_1 (X5Bx5D)) = let a = (X5Bx5D); 0
	(Sumall_split_a_1 (Z_x3Ax3A_ b c)) = let a = (Z_x3Ax3A_ b c); (Sumall_split_b_3 a b c)
	(Sumall_split_b_3 a (Triple d e f) c) = let b = (Triple d e f); (+ (+ (+ (Sumall_1 (c)) (d)) (e)) (f))

(Test1_0) = (Sumall_1 (Triples_1 20))

(Main_0) = (Test1_0)

(PutStrLn_1 a) = a

(Main) = (Main_0)
```

But when I run this with the latest version of HVM (0.1.24) in interpreter mode I get this error:
```
thread 'main' panicked at 'index out of bounds: the len is 4194304 but the index is 4195134', src/runtime.rs:669:6
```
and hvm crashes
When instead I compile it to C the program doesn't crash but it returns 1 instead of 33638 (the correct result)

I also re-wrote the hvm code manually from HVM to make sure that the Agda compiler was not the problem:
```
(If_then_else True  b c) = b
(If_then_else False b c) = c

(Filter p Nil)         = Nil
(Filter p (Cons x xs)) = (If (p x) (Cons x (Filter p xs)) (Filter p xs))

(Append Nil ys)         = ys
(Append (Cons x xs) ys) = (Cons x (Append xs ys))

(Bind Nil f)         = Nil
(Bind (Cons x xs) f) = (Append (f x) (Bind xs f)) 

(Go 0 a)    = Nil
(Go m n) = (Cons n (Go (- m 1) (+ n 1))) 

(Range x y) = (Go (- (+ y 1) x) x)

(Fst (Triple a b c)) = a
(Snd (Triple a b c)) = b
(Trd (Triple a b c)) = c

(Alltriples top) = (Bind (Range 1 top) (@z (Bind (Range 1 z) (@y (Bind (Range 1 y) (@x (Cons (Triple x y z) Nil)))))))

(Cartesian_0) = @t (Cartesian t)
(Cartesian (Triple x y z)) = (== (+ (* x x) (* y y)) (* z z))

(Triples top) = (Filter (Cartesian_0) (Alltriples top))

(Sumall (Cons (Triple x y z) xs)) = (+ (+ (+ x y) z) (Sumall xs))

(Main) = (Sumall (Triples 5))
```
And I get the same error

**Comment by quleuber** [comment]
Hey.
Could you try with a build from `master` and provide a stack trace?

**Comment by judomat** [comment]
Yes sure
I'm already using the latest version from ```master``` (built this morning)
here is the backtrace
```
thread 'main' panicked at 'index out of bounds: the len is 4194304 but the index is 4194304', src/runtime.rs:669:6
stack backtrace:
   0:        0x1084359d2 - std::backtrace_rs::backtrace::libunwind::trace::h95efb3c30cc8d3eb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1084359d2 - std::backtrace_rs::backtrace::trace_unsynchronized::hf55232b46c2b2a5c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1084359d2 - std::sys_common::backtrace::_print_fmt::hd000e024c6701252
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x1084359d2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cae82d438451481
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x1084538bb - core::fmt::write::hb68c3045179d0cad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:        0x1084320ce - std::io::Write::write_fmt::haf84c797e63d79f0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:        0x108437970 - std::sys_common::backtrace::_print::h4051b3c764203017
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x108437970 - std::sys_common::backtrace::print::h946847bf78a6f565
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x108437970 - std::panicking::default_hook::{{closure}}::he18137441e51da1f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:        0x108437656 - std::panicking::default_hook::ha3efe84526f027fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:        0x1084380cd - std::panicking::rust_panic_with_hook::h429a7ddefa5f0258
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:        0x108437df3 - std::panicking::begin_panic_handler::{{closure}}::h9b033a6b15b84a74
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:        0x108435e67 - std::sys_common::backtrace::__rust_end_short_backtrace::hcdd3bec8e0e38aa6
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x108437aba - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:        0x108463f63 - core::panicking::panic_fmt::hf7d6e5207e013f69
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:        0x108463eb6 - core::panicking::panic_bounds_check::h4dad0bcdf31bc1e8
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
  16:        0x10833cb05 - hvm::runtime::normal_go::h5247e127cb28724e
  17:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  18:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  19:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  20:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  21:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  22:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  23:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  24:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  25:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  26:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  27:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  28:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  29:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  30:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  31:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  32:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  33:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  34:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  35:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  36:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  37:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  38:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  39:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  40:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  41:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  42:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  43:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  44:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  45:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  46:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  47:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  48:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  49:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  50:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  51:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  52:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  53:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  54:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  55:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  56:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  57:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  58:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  59:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  60:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  61:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  62:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  63:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  64:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  65:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  66:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  67:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  68:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  69:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  70:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  71:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  72:        0x10833ca29 - hvm::runtime::normal_go::h5247e127cb28724e
  73:        0x10833d0a3 - hvm::runtime::normal::h2c95218f982595c1
  74:        0x108353a63 - hvm::builder::eval_code::hd91ad3899c0749f5
  75:        0x10832a0ca - hvm::run_code::h47e0bbe9c65fb9f7
  76:        0x10832945e - hvm::main::hdd0252ca28bbb046
  77:        0x10832cd96 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c6bb8494405b331
  78:        0x108316d7c - std::rt::lang_start::{{closure}}::hfd2fc9a3fbbf2376
  79:        0x108435105 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0b34a00ab870ad57
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  80:        0x108435105 - std::panicking::try::do_call::hf96b04a014b00830
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  81:        0x108435105 - std::panicking::try::h52320e36f38e53ab
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  82:        0x108435105 - std::panic::catch_unwind::hfb74ccd231e67a94
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  83:        0x108435105 - std::rt::lang_start_internal::{{closure}}::hac12182f9ae31dd1
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  84:        0x108435105 - std::panicking::try::do_call::h7607cb0e1d9db8ca
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  85:        0x108435105 - std::panicking::try::h5bcafddd15b2a478
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  86:        0x108435105 - std::panic::catch_unwind::h74f42b63c70aad90
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  87:        0x108435105 - std::rt::lang_start_internal::hef78d5782ed29805
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  88:        0x10832a859 - _main
```

**Comment by judomat** [comment]
So after some more digging into the issue, I found out that it was mainly my bad but still HVM shouldn't crash or even worse silently give a wrong result (1 instead of 33638 in the compiled version).
Basically, I had written
```
(If_then_else True  b c) = b
(If_then_else False  b c) = c
``` 
When it should have been
```
(If_then_else 1  b c) = b
(If_then_else 0  b c) = c
```
And since it was called many times (with 1 0 whereas it was pattern matching on True False) I'm guessing it was building a huge expression without ever reducing it. 
I think it would be good in a future version to give a proper error message (like ```expression XXX too large, ran out of memory``` or something along these lines) instead of crashing.
