### ISSUE TITLE
 Amazon Linux 2023.5.20240916 (x86_64) Run example hello-world.hvm signal: 11 (SIGSEGV) (core dumped)

### ISSUE THREAD

**Issue by Liberxue** [Kindelia/HVM#430]
## Description:

When running the tests for the`HVM ` project, two specific tests, test_run_examples and test_run_programs, are failing. The failures are characterized by segmentation faults (SIGSEGV) and panics (SIGABRT), and these are leading to discrepancies between expected and actual results. The issue seems related to how certain input files are processed.

#### Clone the HVM repository:

```bash
git clone https://github.com/HigherOrderCO/HVM.git
cd HVM
```
#### Run the tests:

```bash
cargo test
```
#### Error Messages:

```
cargo test -v
       Fresh libc v0.2.155
       Fresh utf8parse v0.2.1
       Fresh anstyle-parse v0.2.4
       Fresh memchr v2.7.2
       Fresh anstyle v1.0.7
       Fresh anstyle-query v1.0.3
       Fresh colorchoice v1.0.1
       Fresh is_terminal_polyfill v1.70.0
       Fresh anstream v0.6.14
       Fresh num_cpus v1.16.0
       Fresh clap_lex v0.7.0
       Fresh cc v1.0.97
       Fresh strsim v0.11.1
       Fresh clap_builder v4.5.2
       Fresh aho-corasick v1.1.3
       Fresh regex-syntax v0.8.3
       Fresh highlight_error v0.1.1
       Fresh TSPL v0.0.13
       Fresh regex-automata v0.4.6
warning: hvm@2.0.22: WARNING: CUDA compiler not found. HVM will not be able to run on GPU.
       Fresh clap v4.5.4
       Fresh bstr v1.9.1
       Fresh log v0.4.21
       Fresh lazy_static v1.4.0
       Fresh same-file v1.0.6
       Fresh walkdir v2.5.0
       Fresh console v0.15.8
       Fresh globset v0.4.14
       Fresh similar v2.5.0
       Fresh linked-hash-map v0.5.6
       Fresh insta v1.39.0
       Fresh hvm v2.0.22 (/home/ec2-user/HVM)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.02s
     Running `/home/ec2-user/HVM/target/debug/deps/hvm-56f1ead42c6b3a14`

running 1 test
test hvm::test_f24 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running `/home/ec2-user/HVM/target/debug/deps/hvm-2b38e5a34b6e6dab`

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running `/home/ec2-user/HVM/target/debug/deps/run-ca6414407ec3a59f`

running 2 tests
test test_run_examples ... stored new snapshot /home/ec2-user/HVM/tests/snapshots/run__io_file@demo_io__main.hvm.snap.new
stored new snapshot /home/ec2-user/HVM/tests/snapshots/run__file@sort_bitonic__main.hvm.snap.new
FAILED
test test_run_programs ... stored new snapshot /home/ec2-user/HVM/tests/snapshots/run__file@empty.hvm.snap.new
FAILED

failures:

---- test_run_examples stdout ----
  testing (io) "/home/ec2-user/HVM/examples/demo_io/main.hvm", C...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/snapshots/run__io_file@demo_io__main.hvm.snap
Snapshot: io_file@demo_io/main.hvm
Source: tests/run.rs:70
Input file: examples/demo_io/main.hvm
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: c_output
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0       │-                                 Apache License
    1       │-Result: ((@IO/Done/tag (@IO/MAGIC (((0 (* x0)) x0) x1))) x1)
          0 │+signal: 11 (SIGSEGV) (core dumped)
────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
snapshot assertion from glob for 'io_file@demo_io/main.hvm' failed in line 70

testing "/home/ec2-user/HVM/examples/sort_bitonic/main.hvm"...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/snapshots/run__file@sort_bitonic__main.hvm.snap
Snapshot: file@sort_bitonic/main.hvm
Source: tests/run.rs:46
Input file: examples/sort_bitonic/main.hvm
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: rust_output
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0       │-Result: 8386560
          0 │+signal: 6 (SIGABRT) (core dumped)
          1 │+thread 'main' panicked at library/core/src/panicking.rs:221:5:
          2 │+unsafe precondition(s) violated: slice::from_raw_parts_mut requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
          3 │+stack backtrace:
          4 │+   0: rust_begin_unwind
          5 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
          6 │+   1: core::panicking::panic_nounwind_fmt::runtime
          7 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:112:18
          8 │+   2: core::panicking::panic_nounwind_fmt
          9 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:122:5
         10 │+   3: core::panicking::panic_nounwind
         11 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:221:5
         12 │+   4: core::slice::raw::from_raw_parts_mut::precondition_check
         13 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ub_checks.rs:68:21
         14 │+   5: core::slice::raw::from_raw_parts_mut
         15 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ub_checks.rs:75:17
         16 │+   6: hvm::hvm::GNet::new
         17 │+             at ./src/hvm.rs:460:25
         18 │+   7: hvm::run
         19 │+             at ./src/main.rs:162:13
         20 │+   8: hvm::main
         21 │+             at ./src/main.rs:72:7
         22 │+   9: core::ops::function::FnOnce::call_once
         23 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
         24 │+note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
         25 │+thread caused non-unwinding panic. aborting.
────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
snapshot assertion from glob for 'file@sort_bitonic/main.hvm' failed in line 46

  testing "/home/ec2-user/HVM/examples/sort_bitonic/main.hvm", C...
thread 'test_run_examples' panicked at tests/run.rs:55:3:
assertion `left == right` failed: "/home/ec2-user/HVM/examples/sort_bitonic/main.hvm": C output does not match rust output
  left: "signal: 11 (SIGSEGV) (core dumped)\n"
 right: "signal: 6 (SIGABRT) (core dumped)\nthread 'main' panicked at library/core/src/panicking.rs:221:5:\nunsafe precondition(s) violated: slice::from_raw_parts_mut requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`\nstack backtrace:\n   0: rust_begin_unwind\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5\n   1: core::panicking::panic_nounwind_fmt::runtime\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:112:18\n   2: core::panicking::panic_nounwind_fmt\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:122:5\n   3: core::panicking::panic_nounwind\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:221:5\n   4: core::slice::raw::from_raw_parts_mut::precondition_check\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ub_checks.rs:68:21\n   5: core::slice::raw::from_raw_parts_mut\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ub_checks.rs:75:17\n   6: hvm::hvm::GNet::new\n             at ./src/hvm.rs:460:25\n   7: hvm::run\n             at ./src/main.rs:162:13\n   8: hvm::main\n             at ./src/main.rs:72:7\n   9: core::ops::function::FnOnce::call_once\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\nthread caused non-unwinding panic. aborting.\n"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:405:23
   3: core::panicking::assert_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:365:5
   4: run::test_file
             at ./tests/run.rs:55:3
   5: core::ops::function::FnMut::call_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:166:5
   6: insta::glob::glob_exec::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/glob.rs:106:13
   7: insta::settings::Settings::bind
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/settings.rs:510:9
   8: insta::glob::glob_exec
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/glob.rs:105:9
   9: run::test_dir
             at ./tests/run.rs:26:3
  10: run::test_run_examples
             at ./tests/run.rs:22:3
  11: run::test_run_examples::{{closure}}
             at ./tests/run.rs:21:23
  12: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_run_programs stdout ----
testing "/home/ec2-user/HVM/tests/programs/empty.hvm"...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/snapshots/run__file@empty.hvm.snap
Snapshot: file@empty.hvm
Source: tests/run.rs:46
Input file: tests/programs/empty.hvm
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: rust_output
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0     0 │ exit status: 101
    1     1 │ thread 'main' panicked at src/ast.rs:545:41:
    2     2 │ missing `@main` definition
    3       │-note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
          3 │+stack backtrace:
          4 │+   0: rust_begin_unwind
          5 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
          6 │+   1: core::panicking::panic_fmt
          7 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
          8 │+   2: core::panicking::panic_display
          9 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:264:5
         10 │+   3: core::option::expect_failed
         11 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:2030:5
         12 │+   4: core::option::Option<T>::expect
         13 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:933:21
         14 │+   5: hvm::ast::Book::build
         15 │+             at ./src/ast.rs:545:21
         16 │+   6: hvm::main
         17 │+             at ./src/main.rs:71:18
         18 │+   7: core::ops::function::FnOnce::call_once
         19 │+             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
         20 │+note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
snapshot assertion from glob for 'file@empty.hvm' failed in line 46

  testing "/home/ec2-user/HVM/tests/programs/empty.hvm", C...
thread 'test_run_programs' panicked at tests/run.rs:55:3:
assertion `left == right` failed: "/home/ec2-user/HVM/tests/programs/empty.hvm": C output does not match rust output
  left: "exit status: 101\nthread 'main' panicked at src/ast.rs:545:41:\nmissing `@main` definition\nstack backtrace:\n   0: rust_begin_unwind\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5\n   1: core::panicking::panic_fmt\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14\n   2: core::panicking::panic_display\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:264:5\n   3: core::option::expect_failed\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:2030:5\n   4: core::option::Option<T>::expect\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:933:21\n   5: hvm::ast::Book::build\n             at ./src/ast.rs:545:21\n   6: hvm::main\n             at ./src/main.rs:77:18\n   7: core::ops::function::FnOnce::call_once\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
 right: "exit status: 101\nthread 'main' panicked at src/ast.rs:545:41:\nmissing `@main` definition\nstack backtrace:\n   0: rust_begin_unwind\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5\n   1: core::panicking::panic_fmt\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14\n   2: core::panicking::panic_display\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:264:5\n   3: core::option::expect_failed\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:2030:5\n   4: core::option::Option<T>::expect\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:933:21\n   5: hvm::ast::Book::build\n             at ./src/ast.rs:545:21\n   6: hvm::main\n             at ./src/main.rs:71:18\n   7: core::ops::function::FnOnce::call_once\n             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:405:23
   3: core::panicking::assert_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:365:5
   4: run::test_file
             at ./tests/run.rs:55:3
   5: core::ops::function::FnMut::call_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:166:5
   6: insta::glob::glob_exec::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/glob.rs:106:13
   7: insta::settings::Settings::bind
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/settings.rs:510:9
   8: insta::glob::glob_exec
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/glob.rs:105:9
   9: run::test_dir
             at ./tests/run.rs:26:3
  10: run::test_run_programs
             at ./tests/run.rs:17:3
  11: run::test_run_programs::{{closure}}
             at ./tests/run.rs:16:23
  12: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_run_examples
    test_run_programs

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.39s
```

## System Settings:

- Rust Version: 1.81.0
- HVM Version: 2.0.22
- gcc Version: 11.4.1
- rust Version: rustc 1.81.0 (eeb90cda1 2024-09-04)
- cargo Version: cargo 1.81.0 (2dbb1af80 2024-08-20)

`$ uname -a`

- Linux ip-xx-xx-41-159.ec2.internal 6.1.109-118.189.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 10 08:59:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- [root@ip-172-31-41-159 HVM]# cat /etc/os-release
- NAME="Amazon Linux"
- VERSION="2023"
- ID="amzn"
- ID_LIKE="fedora"
- VERSION_ID="2023"
- PLATFORM_ID="platform:al2023"
- PRETTY_NAME="Amazon Linux 2023.5.20240916"
- ANSI_COLOR="0;33"
- CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
- HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
- DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
- SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
- BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
- VENDOR_NAME="AWS"
- VENDOR_URL="https://aws.amazon.com/"
- SUPPORT_END="2028-03-15"

 
` $ dmesg | grep -i 'Linux version'`

- [    0.000000] Linux version 6.1.109-118.189.amzn2023.x86_64 (mockbuild@ip-10-0-63-165) (gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), GNU ld version 2.39-6.amzn2023.0.10) #1 SMP PREEMPT_DYNAMIC Tue Sep 10 08:59:12 UTC 2024

`$ hostnamectl `

-  Static hostname: ip-172-31-41-159.ec2.internal
-  Icon name: computer-vm
-  Chassis: vm 🖴
-  Machine ID: ec22f262f98bcbde598b103261f9ca18
-  Boot ID: 883709cf9238453683708a9359ed1e57
-  Virtualization: xen
-  Operating System: Amazon Linux 2023.5.20240916
-  CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2023
-  Kernel: Linux 6.1.109-118.189.amzn2023.x86_64
-  Architecture: x86-64
-  Hardware Vendor: Xen
-  Hardware Model: HVM domU
-  Firmware Version: 4.11.amazon

` dmesg | grep 'segfault'`

`
[  398.007544] hvm[29181]: segfault at 0 ip 000055fee441d902 sp 00007ffc33889d48 error 6 in hvm[55fee43eb000+143000] likely on CPU 0 (core 0, socket 0)
[  564.109013] hvm[29640]: segfault at 0 ip 0000556aab2e0902 sp 00007ffca2831f18 error 6 in hvm[556aab2ae000+143000] likely on CPU 0 (core 0, socket 0)
[  580.704984] hvm[29870]: segfault at 0 ip 000055c0658d2902 sp 00007ffd8dfc3d68 error 6 in hvm[55c0658a0000+143000] likely on CPU 0 (core 0, socket 0)
[  602.029839] hvm[30114]: segfault at 0 ip 00005582aab58902 sp 00007ffdc07f9d48 error 6 in hvm[5582aab26000+143000] likely on CPU 0 (core 0, socket 0)
[  670.203708] hvm[30714]: segfault at 0 ip 000055557e0d8902 sp 00007ffca2d7bbb8 error 6 in hvm[55557e0a6000+143000] likely on CPU 0 (core 0, socket 0)
[  981.651397] hvm[32332]: segfault at 0 ip 0000555c45f2caa2 sp 00007fffb7951b78 error 6 in hvm[555c45efc000+140000] likely on CPU 0 (core 0, socket 0)
[ 1018.068066] hvm[32437]: segfault at 0 ip 000055f3c54f2aa2 sp 00007ffd7e0ff9d8 error 6 in hvm[55f3c54c2000+140000] likely on CPU 0 (core 0, socket 0)
[ 1031.228363] hvm[32450]: segfault at 0 ip 000055fe6e812aa2 sp 00007fffd1438ed8 error 6 in hvm[55fe6e7e2000+140000] likely on CPU 0 (core 0, socket 0)
[ 1113.421636] hvm[33549]: segfault at 7ffffffc ip 000055a9f4ff793d sp 00007ffe9cb4ad48 error 6 in hvm[55a9f4fd1000+140000] likely on CPU 0 (core 0, socket 0)
[ 1124.220687] hvm[33617]: segfault at 0 ip 000055602c8d3aa2 sp 00007ffe378876c8 error 6 in hvm[55602c8a3000+140000] likely on CPU 0 (core 0, socket 0)
[ 1145.427506] hvm[33651]: segfault at 0 ip 000055a1c642faa2 sp 00007fff0f4706c8 error 6 in hvm[55a1c63ff000+140000] likely on CPU 0 (core 0, socket 0)
[ 1158.262371] hvm[33664]: segfault at 0 ip 000055b428e7eaa2 sp 00007ffce59ee268 error 6 in hvm[55b428e4e000+140000] likely on CPU 0 (core 0, socket 0)
[ 1224.535016] hvm[33762]: segfault at 7ffffffc ip 00005635718a093d sp 00007ffeecb86a98 error 6 in hvm[56357187a000+140000] likely on CPU 0 (core 0, socket 0)
[ 1389.015507] hvm[35611]: segfault at 0 ip 00005595a21aabe2 sp 00007ffd1d892418 error 6 in hvm[5595a2129000+28d000] likely on CPU 0 (core 0, socket 0)
[ 1389.410961] hvm[35632]: segfault at 0 ip 0000556c6de32be2 sp 00007ffe8c5f6728 error 6 in hvm[556c6ddb1000+28d000] likely on CPU 0 (core 0, socket 0)
[ 1389.588080] hvm[35655]: segfault at 0 ip 0000555965806be2 sp 00007ffcb03ba678 error 6 in hvm[555965785000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2041.169311] hvm[36449]: segfault at 0 ip 0000556190bfabe2 sp 00007ffc881920b8 error 6 in hvm[556190b79000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2041.396156] hvm[36472]: segfault at 0 ip 000055f9428f4be2 sp 00007fff78049228 error 6 in hvm[55f942873000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2041.563872] hvm[36494]: segfault at 0 ip 0000562cadac6be2 sp 00007fff67b87308 error 6 in hvm[562cada45000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2097.191472] hvm[36532]: segfault at 0 ip 000055bf80b0bbe2 sp 00007fff35782bc8 error 6 in hvm[55bf80a8a000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2097.488281] hvm[36611]: segfault at 0 ip 000055601728fbe2 sp 00007ffed8e40b48 error 6 in hvm[55601720e000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2097.656396] hvm[36633]: segfault at 0 ip 00005629f920cbe2 sp 00007fffabd1cfa8 error 6 in hvm[5629f918b000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2333.043177] hvm[36929]: segfault at 0 ip 00005614d2c59be2 sp 00007fffe4bf8368 error 6 in hvm[5614d2bd8000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2333.293003] hvm[36949]: segfault at 0 ip 0000563acdee0be2 sp 00007fff0b8c4838 error 6 in hvm[563acde5f000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2333.461925] hvm[36971]: segfault at 0 ip 0000564c3f7a2be2 sp 00007ffe6f9b9e48 error 6 in hvm[564c3f721000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2359.768501] hvm[37006]: segfault at 0 ip 000055a4e32d6be2 sp 00007fff63e57038 error 6 in hvm[55a4e3255000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2360.076172] hvm[37086]: segfault at 0 ip 0000555a3347fbe2 sp 00007ffd215ff798 error 6 in hvm[555a333fe000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2360.241514] hvm[37109]: segfault at 0 ip 0000562c12185be2 sp 00007ffd20664298 error 6 in hvm[562c12104000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2458.316079] hvm[37239]: segfault at 0 ip 000055dad4698be2 sp 00007ffe5b735278 error 6 in hvm[55dad4617000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2458.633213] hvm[37259]: segfault at 0 ip 000056017fa88be2 sp 00007ffdb823ac08 error 6 in hvm[56017fa07000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2518.062348] hvm[37317]: segfault at 0 ip 000055da183efbe2 sp 00007ffe8cfe9298 error 6 in hvm[55da1836e000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2518.386125] hvm[37396]: segfault at 0 ip 000055d5febd1be2 sp 00007ffe69970fb8 error 6 in hvm[55d5feb50000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2541.632573] hvm[37435]: segfault at 0 ip 000055ee88f16be2 sp 00007ffeffcedf88 error 6 in hvm[55ee88e95000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2541.865520] hvm[37455]: segfault at 0 ip 000055b008089be2 sp 00007ffe9afd0a48 error 6 in hvm[55b008008000+28d000] likely on CPU 0 (core 0, socket 0)
[ 2699.936154] hvm[37667]: segfault at 7ffffffc ip 00005576ef28393d sp 00007ffc37880fe8 error 6 in hvm[5576ef25d000+140000] likely on CPU 0 (core 0, socket 0)
[ 2705.590260] hvm[37736]: segfault at 0 ip 000055e27e2cdaa2 sp 00007fff442eca38 error 6 in hvm[55e27e29d000+140000] likely on CPU 0 (core 0, socket 0)`

**Comment by edusporto** [comment]
How much memory was allocated to the instance you used to test? HVM-32 currently allocates a fixed amount of memory of about 6 GB on startup.

**Comment by Liberxue** [comment]
> How much memory was allocated to the instance you used to test? HVM-32 currently allocates a fixed amount of memory of about 6 GB on startup.

current about 2GB memory 😅
@edusporto  THX~~ 

I ran the test on an 8GB memory  (Linux system with version 6.1.109-118.189.amzn2023.x86_64), and everything is okay
