### ISSUE TITLE
[armh] capacity overflow in raw_vec when interpreting readme example

### ISSUE THREAD

**Issue by blakehawkins** [Kindelia/HVM#93]
```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
$ cat main.hvm
// Creates a tree with `2^n` elements
(Gen 0) = (Leaf 1)
(Gen n) = (Node (Gen(- n 1)) (Gen(- n 1)))

// Adds all elements of a tree
(Sum (Leaf x))   = x
(Sum (Node a b)) = (+ (Sum a) (Sum b))

// Performs 2^n additions in parallel
(Main n) = (Sum (Gen n))
```

```
$ RUST_BACKTRACE=1 hvm r main 3
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:509:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: alloc::raw_vec::capacity_overflow
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/raw_vec.rs:509:5
   4: hvm::builder::eval_code
   5: hvm::run_code
   6: hvm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by VictorTaelin** [comment]
It should output this:

```
$ hvm r main 3
Rewrites: 59 (0.01 MR/s)
Mem.Size: 47

8
```

@quleuber @rigille can you try to replicate? I guess we'd need a Raspberry, or at least a way to emulate it. Would be nice if we could run on it, and I don't see reasons not to. Since you guys are busy, perhaps we can flag this as issue as welcoming contributions?

**Comment by blakehawkins** [comment]
Just to confirm, this issue is still occurring on 0.1.20

@quleuber this was tested on a raspberry pi 3B:

```
$ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1400.0000
CPU min MHz:         600.0000
BogoMIPS:            38.40
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```

**Comment by VictorTaelin** [comment]
Is the issue gone? Please let me know if not.
